# Generated by Django 4.1.1 on 2022-09-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('lastName', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambulance')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
