# Generated by Django 4.1.1 on 2022-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='phone',
            field=models.CharField(default='6640000000', max_length=15),
        ),
    ]
