# Generated by Django 4.1.1 on 2022-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambulancedriver_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancedriver',
            name='phone',
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='6640000000', max_length=15),
        ),
    ]
